
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AspNetRoleBasedSecurity
{

using System;
    using System.Collections.Generic;
    
public partial class Infractio
{

    public int Id { get; set; }

    public string Title { get; set; }

    public string Tags { get; set; }

    public string Subject { get; set; }

    public string User_name { get; set; }

    public System.DateTime DatePosted { get; set; }

    public string Status { get; set; }

    public string Samples { get; set; }

    public Nullable<long> PageView { get; set; }

    public string Approver_name { get; set; }

}

}
