//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetRoleBasedSecurity
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int NotificationId { get; set; }
        public string Title { get; set; }
        public string User_name { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public string Status { get; set; }
        public string Approver_name { get; set; }
        public string ReadStatus { get; set; }
        public string ClosedStatus { get; set; }
        public Nullable<int> InfractionId { get; set; }
        public Nullable<System.DateTime> reviewdate { get; set; }
    }
}
